# Generated by Django 3.0.4 on 2020-03-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweet_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
