# Generated by Django 3.0.4 on 2020-03-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweet_tweet_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributePythonTip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('python_tip', models.TextField(max_length=140)),
                ('name_or_id', models.CharField(blank=True, max_length=200)),
                ('your_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
